SELECT *
FROM "Artist"
WHERE LOWER ("Name") = 'nirvana'
OR UPPER ("Name") = 'NIRVANA';

-- Listar nombre y apellido de personas que hayan comprado cancions de 'Led Zeppelin' y 'Deep Purple', Usando JOINS e INTERSECT;
SELECT "FirstName", "LastName"
FROM "Customer"
WHERE "CustomerId" IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Led Zeppelin')))))
AND "CustomerId" IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Deep Purple')))));
--INTERSECT                                                                                                          
SELECT "FirstName", "LastName"
FROM "Customer"
WHERE "CustomerId" IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Led Zeppelin')))))
INTERSECT
SELECT "FirstName", "LastName"
FROM "Customer"
WHERE "CustomerId" IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Deep Purple')))));
                                                                                                          
-- Listar el identificador y nombre de lista de repoduccion de aquellas que tengan canciones de artistas con nirvana, metallica o iron maiden. Usando
-- UNION y otra version con JOINS, etc.
SELECT DISTINCT "Name", "PlaylistId"
FROM "Playlist" WHERE "PlaylistId" IN (SELECT "PlaylistId"
                                       FROM "PlaylistTrack"
                                       WHERE "TrackId" IN (SELECT "TrackId"
                                                           FROM "Track"
                                                           WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                               FROM "Album"
                                                                               WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                    FROM "Artist"
                                                                                                    WHERE "Name" IN ('Nirvana','Metallica','Iron Maiden')))));
                                        
--UNION
SELECT DISTINCT "Name", "PlaylistId"
FROM "Playlist"
WHERE "PlaylistId" IN (SELECT "PlaylistId"
                       FROM "PlaylistTrack"
                       WHERE "TrackId" IN (SELECT "TrackId"
                                           FROM "Track"
                                           WHERE "AlbumId" IN (SELECT "AlbumId"
                                                               FROM "Album"
                                                               WHERE "ArtistId" = (SELECT "ArtistId"
                                                                                   FROM "Artist"
                                                                                   WHERE "Name" = 'Nirvana'))))
UNION
SELECT DISTINCT "Name", "PlaylistId"
FROM "Playlist"
WHERE "PlaylistId" IN (SELECT "PlaylistId"
                       FROM "PlaylistTrack"
                       WHERE "TrackId" IN (SELECT "TrackId"
                                           FROM "Track"
                                           WHERE "AlbumId" IN (SELECT "AlbumId"
                                                               FROM "Album"
                                                               WHERE "ArtistId" = (SELECT "ArtistId"
                                                                                   FROM "Artist"
                                                                                   WHERE "Name" = 'Metallica'))))
UNION
SELECT DISTINCT "Name", "PlaylistId"
FROM "Playlist"
WHERE "PlaylistId" IN (SELECT "PlaylistId"
                       FROM "PlaylistTrack"
                       WHERE "TrackId" IN (SELECT "TrackId"
                                           FROM "Track"
                                           WHERE "AlbumId" IN (SELECT "AlbumId"
                                                               FROM "Album"
                                                               WHERE "ArtistId" = (SELECT "ArtistId"
                                                                                   FROM "Artist"
                                                                                   WHERE "Name" = 'Iron Maiden'))));
                                                                                   
-- Listar nombre y apellido de personas que hayan comprado canciones de 'Led Zeppelin' y 'Deep Purple' pero no de 'Black Sabbath'. Usando JOINS y/o SUBCONSULTAS y EXCEPT;
SELECT "FirstName", "LastName"
FROM "Customer"
WHERE "CustomerId" IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Led Zeppelin')))))
AND "CustomerId" IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Deep Purple')))))
AND "CustomerId" NOT IN (SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Black Sabbath')))));
                                                                                                          
--EXCEPT
SELECT "FirstName", "LastName"
FROM "Customer"
WHERE "CustomerId" IN (
                       SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Led Zeppelin'))))
                       INTERSECT
                       SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Deep Purple'))))
                       EXCEPT
                       SELECT "CustomerId"
                       FROM "Invoice"
                       WHERE "InvoiceId" IN (SELECT "InvoiceId"
                                             FROM "InvoiceLine"
                                             WHERE "TrackId" IN (SELECT "TrackId"
                                                                 FROM "Track"
                                                                 WHERE "AlbumId" IN (SELECT "AlbumId"
                                                                                     FROM "Album"
                                                                                     WHERE "ArtistId" IN (SELECT "ArtistId"
                                                                                                          FROM "Artist"
                                                                                                          WHERE "Name" = 'Black Sabbath')))));